# set up aliases
# --------------
# for command line
alias ls="ls -G"

# Location aliases
alias h="cd ~" # There's no place like home...
alias pats="cd /Users/lheimann/67-272-S11/PATS"
alias labs="cd /Users/lheimann/67-272-S11/labs"


# --------------
# for rails2
alias ss='script/server' # rails: script/server
alias sc='script/console' # rails: script/console
alias sg='script/generate' # rails: script/generate
alias sgs='script/generate scaffold' # rails: script/generate
alias sgm='script/generate migration' # rails: script/generate
alias sgns='script/generate nifty_scaffold' # use nifty_scaffold
alias rdm='rake db:migrate'
alias rdp='rake db:populate'  # assuming a populate task exists


# --------------
# new for rails3
alias rn='rails new'
alias rs='rails server'
alias rc='rails console'
alias rdc='rails dbconsole'
alias rg='rails generate'
alias rgs='rails generate scaffold'
alias rgm='rails generate migration'
alias rgns='rails generate nifty:scaffold'

# Note: still have access to 'rdm' and 'rdp' from above

# --------------
# for git
alias g="git status"	# status of files
alias ga="git add"		# add a file to staging
alias gr="git rm" 		# remove a file 
alias gc="git commit"	# commit files to repo
alias gp="git push"		# push to repo
alias gpl="git pull"	# pull from repo
alias gpom="git push origin master" # typically to send to github
alias gco="git checkout" # checkout
alias gb="git branch"	# for branching
alias gm="git merge"	# for merging
alias gi="git instaweb --httpd webrick" # to visualize in browser
alias gl="git gl"			# pretty log (specs in .gitconfig)
alias gd="git diff"		# diff a file